export enum PublicationsAction {
  PUBLICATIONS_LOADING_START = "PUBLICATIONS_LOADING_START",
  PUBLICATIONS_LOADING_END = "PUBLICATIONS_LOADING_END",

  GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS",
  GET_PUBLICATIONS_NOT_FOUND = "GET_PUBLICATIONS_NOT_FOUND",
  GET_PUBLICATIONS_HTTP_INTERNAL_ERROR = "GET_PUBLICATIONS_HTTP_INTERNAL_ERROR",
  GET_PUBLICATIONS_ERROR = "GET_PUBLICATIONS_ERROR",
}
