export enum PublicationsAction {
  PUBLICATIONS_LOADING_START = "PUBLICATIONS_LOADING_START",
  PUBLICATIONS_LOADING_END = "PUBLICATIONS_LOADING_END",

  GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS",
  GET_PUBLICATIONS_NOT_FOUND = "GET_PUBLICATIONS_NOT_FOUND",
  GET_PUBLICATIONS_HTTP_INTERNAL_ERROR = "GET_PUBLICATIONS_HTTP_INTERNAL_ERROR",
  GET_PUBLICATIONS_ERROR = "GET_PUBLICATIONS_ERROR",

  GET_PUBLICATION_SUCCESS = "GET_PUBLICATION_SUCCESS",
  GET_PUBLICATION_NOT_FOUND = "GET_PUBLICATION_NOT_FOUND",
  GET_PUBLICATION_HTTP_INTERNAL_ERROR = "GET_PUBLICATION_HTTP_INTERNAL_ERROR",
  GET_PUBLICATION_ERROR = "GET_PUBLICATION_ERROR",

  POST_PUBLICATIONS_SUCCESS = "POST_PUBLICATIONS_SUCCESS",
  POST_PUBLICATIONS_NOT_FOUND = "POST_PUBLICATIONS_NOT_FOUND",
  POST_PUBLICATIONS_HTTP_INTERNAL_ERROR = "POST_PUBLICATIONS_HTTP_INTERNAL_ERROR",
  POST_PUBLICATIONS_ERROR = "POST_PUBLICATIONS_ERROR",
}
