export enum SocialAccountsAction {
  SOCIAL_ACCOUNTS_LOADING_START = "SOCIAL_ACCOUNTS_LOADING_START",
  SOCIAL_ACCOUNTS_LOADING_END = "SOCIAL_ACCOUNTS_LOADING_END",

  LOGIN_URL_LOADING_START = "LOGIN_URL_LOADING_START",
  LOGIN_URL_LOADING_END = "LOGIN_URL_LOADING_END",

  LOADING_START = "LOADING_START",
  LOADING_END = "LOADING_END",

  GET_SOCIAL_ACCOUNTS_SUCCESS = "GET_SOCIAL_ACCOUNTS_SUCCESS",
  GET_SOCIAL_ACCOUNTS_NOT_FOUND = "GET_SOCIAL_ACCOUNTS_NOT_FOUND",
  GET_SOCIAL_ACCOUNTS_HTTP_INTERNAL_ERROR = "GET_SOCIAL_ACCOUNTS_HTTP_INTERNAL_ERROR",
  GET_SOCIAL_ACCOUNTS_ERROR = "GET_SOCIAL_ACCOUNTS_ERROR",

  DELETE_SOCIAL_ACCOUNT_SUCCESS = "DELETE_SOCIAL_ACCOUNT_SUCCESS",
  DELETE_SOCIAL_ACCOUNT_NOT_FOUND = "DELETE_SOCIAL_ACCOUNT_NOT_FOUND",
  DELETE_SOCIAL_ACCOUNT_HTTP_INTERNAL_ERROR = "DELETE_SOCIAL_ACCOUNT_HTTP_INTERNAL_ERROR",
  DELETE_SOCIAL_ACCOUNT_ERROR = "DELETE_SOCIAL_ACCOUNT_ERROR",

  GET_FACEBOOK_LOGIN_URL_SUCCESS = "GET_FACEBOOK_LOGIN_URL_SUCCESS",
  GET_FACEBOOK_LOGIN_URL_NOT_FOUND = "GET_FACEBOOK_LOGIN_URL_NOT_FOUND",
  GET_FACEBOOK_LOGIN_URL_HTTP_INTERNAL_ERROR = "GET_FACEBOOK_LOGIN_URL_HTTP_INTERNAL_ERROR",
  GET_FACEBOOK_LOGIN_URL_ERROR = "GET_FACEBOOK_LOGIN_URL_ERROR",

  GET_TWITTER_LOGIN_URL_SUCCESS = "GET_TWITTER_LOGIN_URL_SUCCESS",
  GET_TWITTER_LOGIN_URL_NOT_FOUND = "GET_TWITTER_LOGIN_URL_NOT_FOUND",
  GET_TWITTER_LOGIN_URL_HTTP_INTERNAL_ERROR = "GET_TWITTER_LOGIN_URL_HTTP_INTERNAL_ERROR",
  GET_TWITTER_LOGIN_URL_ERROR = "GET_TWITTER_LOGIN_URL_ERROR",

  GET_LINKEDIN_LOGIN_URL_SUCCESS = "GET_LINKEDIN_LOGIN_URL_SUCCESS",
  GET_LINKEDIN_LOGIN_URL_NOT_FOUND = "GET_LINKEDIN_LOGIN_URL_NOT_FOUND",
  GET_LINKEDIN_LOGIN_URL_HTTP_INTERNAL_ERROR = "GET_LINKEDIN_LOGIN_URL_HTTP_INTERNAL_ERROR",
  GET_LINKEDIN_LOGIN_URL_ERROR = "GET_LINKEDIN_LOGIN_URL_ERROR",
}
