export enum SocialAccountsAction {
  SOCIAL_ACCOUNTS_LOADING_START = "SOCIAL_ACCOUNTS_LOADING_START",
  SOCIAL_ACCOUNTS_LOADING_END = "SOCIAL_ACCOUNTS_LOADING_END",

  GET_SOCIAL_ACCOUNTS_SUCCESS = "GET_SOCIAL_ACCOUNTS_SUCCESS",
  GET_SOCIAL_ACCOUNTS_NOT_FOUND = "GET_SOCIAL_ACCOUNTS_NOT_FOUND",
  GET_SOCIAL_ACCOUNTS_HTTP_INTERNAL_ERROR = "GET_SOCIAL_ACCOUNTS_HTTP_INTERNAL_ERROR",
  GET_SOCIAL_ACCOUNTS_ERROR = "GET_SOCIAL_ACCOUNTS_ERROR",
}
