export enum UserAction {
  USER_LOADING_START = "USER_LOADING_START",
  USER_LOADING_END = "USER_LOADING_END",

  GET_WORKSPACES_SUCCESS = "GET_WORKSPACES_SUCCESS",
  GET_WORKSPACES_NOT_FOUND = "GET_WORKSPACES_NOT_FOUND",
  GET_WORKSPACES_HTTP_INTERNAL_ERROR = "GET_WORKSPACES_HTTP_INTERNAL_ERROR",
  GET_WORKSPACES_ERROR = "GET_WORKSPACES_ERROR",

  GET_WORKSPACE_SUCCESS = "GET_WORKSPACE_SUCCESS",
  GET_WORKSPACE_NOT_FOUND = "GET_WORKSPACE_NOT_FOUND",
  GET_WORKSPACE_HTTP_INTERNAL_ERROR = "GET_WORKSPACE_HTTP_INTERNAL_ERROR",
  GET_WORKSPACE_ERROR = "GET_WORKSPACE_ERROR",
}
