export enum OrganizationsAction {
  ORGANIZATIONS_LOADING_START = "ORGANIZATIONS_LOADING_START",
  ORGANIZATIONS_LOADING_END = "ORGANIZATIONS_LOADING_END",

  GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS",
  GET_ORGANIZATIONS_NOT_FOUND = "GET_ORGANIZATIONS_NOT_FOUND",
  GET_ORGANIZATIONS_HTTP_INTERNAL_ERROR = "GET_ORGANIZATIONS_HTTP_INTERNAL_ERROR",
  GET_ORGANIZATIONS_ERROR = "GET_ORGANIZATIONS_ERROR",

  GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS",
  GET_ORGANIZATION_NOT_FOUND = "GET_ORGANIZATION_NOT_FOUND",
  GET_ORGANIZATION_HTTP_INTERNAL_ERROR = "GET_ORGANIZATION_HTTP_INTERNAL_ERROR",
  GET_ORGANIZATION_ERROR = "GET_ORGANIZATION_ERROR",
}
