export enum PostsAction {
  GET_POST_LOADING_START = "GET_POST_LOADING_START",
  GET_POST_LOADING_END = "GET_POST_LOADING_END",

  LOADING_START = "LOADING_START",
  LOADING_END = "LOADING_END",

  GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS",
  GET_POSTS_NOT_FOUND = "GET_POSTS_NOT_FOUND",
  GET_POSTS_HTTP_INTERNAL_ERROR = "GET_POSTS_HTTP_INTERNAL_ERROR",
  GET_POSTS_ERROR = "GET_POSTS_ERROR",

  GET_POST_SUCCESS = "GET_POST_SUCCESS",
  GET_POST_NOT_FOUND = "GET_POST_NOT_FOUND",
  GET_POST_HTTP_INTERNAL_ERROR = "GET_POST_HTTP_INTERNAL_ERROR",
  GET_POST_ERROR = "GET_POST_ERROR",
}
