export enum SocialNetworksAction {
  SOCIAL_NETWORKS_LOADING_START = "SOCIAL_NETWORKS_LOADING_START",
  SOCIAL_NETWORKS_LOADING_END = "SOCIAL_NETWORKS_LOADING_END",

  GET_SOCIAL_NETWORKS_SUCCESS = "GET_SOCIAL_NETWORKS_SUCCESS",
  GET_SOCIAL_NETWORKS_NOT_FOUND = "GET_SOCIAL_NETWORKS_NOT_FOUND",
  GET_SOCIAL_NETWORKS_HTTP_INTERNAL_ERROR = "GET_SOCIAL_NETWORKS_HTTP_INTERNAL_ERROR",
  GET_SOCIAL_NETWORKS_ERROR = "GET_SOCIAL_NETWORKS_ERROR",
}
