export enum SocialNetworksAction {
  SOCIAL_NETWORKS_LOADING_START = "SOCIAL_NETWORKS_LOADING_START",
  SOCIAL_NETWORKS_LOADING_END = "SOCIAL_NETWORKS_LOADING_END",

  GET_SOCIAL_NETWORKS_SUCCESS = "GET_SOCIAL_NETWORKS_SUCCESS",
  GET_SOCIAL_NETWORKS_NOT_FOUND = "GET_SOCIAL_NETWORKS_NOT_FOUND",
  GET_SOCIAL_NETWORKS_HTTP_INTERNAL_ERROR = "GET_SOCIAL_NETWORKS_HTTP_INTERNAL_ERROR",
  GET_SOCIAL_NETWORKS_ERROR = "GET_SOCIAL_NETWORKS_ERROR",

  GET_SOCIAL_NETWORKS_BY_CODE_SUCCESS = "GET_SOCIAL_NETWORKS_BY_CODE_SUCCESS",
  GET_SOCIAL_NETWORKS_BY_CODE_NOT_FOUND = "GET_SOCIAL_NETWORKS_BY_CODE_NOT_FOUND",
  GET_SOCIAL_NETWORKS_BY_CODE_HTTP_INTERNAL_ERROR = "GET_SOCIAL_NETWORKS_BY_CODE_HTTP_INTERNAL_ERROR",
  GET_SOCIAL_NETWORKS_BY_CODE_ERROR = "GET_SOCIAL_NETWORKS_BY_CODE_ERROR",

  POST_SOCIAL_NETWORKS_VALIDATE_SUCCESS = "POST_SOCIAL_NETWORKS_VALIDATE_SUCCESS",
  POST_SOCIAL_NETWORKS_VALIDATE_NOT_FOUND = "POST_SOCIAL_NETWORKS_VALIDATE_NOT_FOUND",
  POST_SOCIAL_NETWORKS_VALIDATE_HTTP_INTERNAL_ERROR = "POST_SOCIAL_NETWORKS_VALIDATE_HTTP_INTERNAL_ERROR",
  POST_SOCIAL_NETWORKS_VALIDATE_ERROR = "POST_SOCIAL_NETWORKS_VALIDATE_ERROR",

  GET_SOCIAL_NETWORKS_CONNECT_SUCCESS = "GET_SOCIAL_NETWORKS_CONNECT_SUCCESS",
  GET_SOCIAL_NETWORKS_CONNECT_NOT_FOUND = "GET_SOCIAL_NETWORKS_CONNECT_NOT_FOUND",
  GET_SOCIAL_NETWORKS_CONNECT_HTTP_INTERNAL_ERROR = "GET_SOCIAL_NETWORKS_CONNECT_HTTP_INTERNAL_ERROR",
  GET_SOCIAL_NETWORKS_CONNECT_ERROR = "GET_SOCIAL_NETWORKS_CONNECT_ERROR",
}
